radix: radix.c
	gcc -o radix radix.c helpers.c

stack: stack.c
	gcc -w -o stack stack.c helpers.c

copy: copy.c
	gcc -o copy copy.c

read: read.c
	gcc -o read read.c

nsfw: nsfw.c
	gcc -o nsfw nsfw.c

in: in.c
	gcc -o in in.c

out: out.c
	gcc -o out out.c

clean:
	rm radix stack copy read nsfw in out
